title: No Mans Explorer
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.4851064
  rhythmicContrast: 1
  brandColors:
    - '#3f3f3f'
    - '#ffffff'
    - '#b6494e'
    - '#979797'
    - '#d7d7d7'
  lightness: 0.7368421
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: No Mans Explorer
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3007519
layout_spectrum: 0.38734
