name: No Mans Explorer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02952
title: No Mans Explorer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f3f3f'
    - '#ffffff'
    - '#b6494e'
    - '#979797'
    - '#d7d7d7'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
