name: Nomansexplorer
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#DC143C'
    - '#BFBFBF'
    - '#7F7F7F'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
