typography_spectrum: 0.3007519
color:
  brandColors:
    - '#3f3f3f'
    - '#ffffff'
    - '#b6494e'
    - '#979797'
    - '#d7d7d7'
  brandStrength: 0
  lightness: 0.7368421
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.38734
analytics:
  google: null
  facebook: null
  twitter: null
name: No Mans Explorer
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: No Mans Explorer
purpose: []
