layout_spectrum: 0.5591398
color:
  saturation: 0.7419355
  brandStrength: 0.8494624
  lightness: 0.7544803
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#DC143C'
    - '#BFBFBF'
    - '#7F7F7F'
  rhythmicContrast: 0.6684588
typography_spectrum: 0.297491
name: Nomansexplorer
