typography_spectrum: 0.157304628752172
color:
  brandColors:
    - '#3f3f3f'
    - '#ffffff'
    - '#b6494e'
    - '#979797'
    - '#d7d7d7'
  brandStrength: 0
  lightness: 0.7368421
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8318006503395736
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/13bf219a-a836-42e5-b608-a76b35dd6cc7.jpg
name: No Mans Explorer
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8cb38229-99c9-4f3b-adc6-39d5eaf26ac2.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: No Mans Explorer
description: Follow The Explorer
purpose: []
